"""add resource_acl_mappings

Revision ID: 720a635c0649
Revises: d05fmgudxt94
Create Date: 2026-07-02 19:06:24.416500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '720a635c0649'
down_revision: Union[str, Sequence[str], None] = 'd05fmgudxt94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_acl_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('resource_key', sa.Text(), nullable=False),
    sa.Column('acl_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'resource_key', name='uq_resource_acl_mappings_type_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_acl_mappings')
    # ### end Alembic commands ###
